# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run.
on:
  schedule:
    - cron: "0 0 1 * *" # monthly
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare_env:
    name: Prepare build version
    runs-on: ubuntu-latest
    env:
      EMACS_REPO: https://github.com/kiennq/emacs.git
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Get build version
        id: vars
        run: |
          mkdir -p ./git/emacs
          cd ./git/emacs/
          git clone --depth 1 $EMACS_REPO .
          commit=`date +'%Y%m%d'`.`git rev-parse --short=7 HEAD`
          major_ver=`cat configure.ac | grep -Po 'AC_INIT\(.*\[\K\d+'`
          version=`echo ${major_ver}.${{ github.run_number }}.${commit}`
          # bail out if the release existed
          echo "version=${version}" >> $GITHUB_ENV
    outputs:
      repo: ${{ env.EMACS_REPO }}
      version: ${{ env.version }}

  build:
    needs: prepare_env
    name: Build Emacs
    # Matrix strategy from
    # https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            shell: powershell
            msystem: MINGW64
          - os: windows-latest
            shell: powershell
            msystem: UCRT64
          - os: ubuntu-latest
            shell: bash

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    env:
      MSYS2_DIR: C:\msys64
      EMACS_REPO: ${{ needs.prepare_env.outputs.repo }}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Msys2
        uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          msystem: ${{ matrix.msystem }}
          release: false

      # This is the shortest job, but in this case it pulls all MSYS/MINGW64
      - name: Clone Emacs
        if: runner.os == 'Windows'
        run: .\emacs-build.cmd --clone --repo https://github.com/kiennq/emacs.git --depth 1

      - name: Clone Emacs
        if: runner.os != 'Windows'
        run: |
          mkdir -p ./git/emacs
          cd ./git/emacs/
          git clone --depth 1 $EMACS_REPO .

      - name: Build Emacs
        if: runner.os == 'Windows'
        # Require --nativecomp and --with-* flags, else the deps will not be included properly
        run: |
          .\emacs-build.cmd --nativecomp --slim --with-rsvg --build

      - name: Package Emacs
        if: runner.os == 'Windows'
        run: |
          .\emacs-build.cmd --nativecomp --slim --with-rsvg --pack-all

      - name: Build and pack Emacs
        if: runner.os != 'Windows'
        run: |
          chmod 755 ./emacs-build-unix.sh
          mkdir -p ./zips
          ./emacs-build-unix.sh -s ./git/emacs/ -v ${{ needs.prepare_env.outputs.version }} -d ./zips

      # Upload release for each build
      - name: Upload binaries to release
        id: upload_release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: ./zips/*{-full.zip,.deb}
          file_glob: true
          tag: v${{ needs.prepare_env.outputs.version }}
          release_name: emacs_${{ needs.prepare_env.outputs.version }}
          draft: false
          prerelease: false
